/* Generated By:JavaCC: Do not edit this line. WriteConstants.java */
package write;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WriteConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int word = 23;
  /** RegularExpression Id. */
  int NUM = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/\"",
    "\":\"",
    "\"\\u201c\"",
    "\".\"",
    "\"PARAGRAPH\"",
    "\"IMAGE\"",
    "\"WITH\"",
    "\"SOURCE\"",
    "\"ADD\"",
    "\"HEADING\"",
    "\"LINK\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
    "\"http\"",
    "\"com\"",
    "\"AND\"",
    "\"WITH LINK\"",
    "<word>",
    "<NUM>",
  };

}
