/* Generated By:JavaCC: Do not edit this line. GenerateConstants.java */
package generate;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GenerateConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int word = 24;
  /** RegularExpression Id. */
  int NUM = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"/\"",
    "\":\"",
    "\"\\\'\"",
    "\".\"",
    "\"_\"",
    "\" \"",
    "\"\\\"\"",
    "\"\\\" \"",
    "\"\\n\"",
    "\"PARAGRAPH \"",
    "\"IMAGE \"",
    "\"WITH \"",
    "\"SOURCE \"",
    "\"ADD \"",
    "\"HEADING \"",
    "\"LINK \"",
    "\"TEXT \"",
    "\"COLOR \"",
    "\"FONT \"",
    "\"AND \"",
    "\"WITH LINK \"",
    "<word>",
    "<NUM>",
  };

}
